### ISSUE TITLE
Upgrade to react-redux@6.x (has issues)

### ISSUE THREAD

**Issue by jahed** [frontiernav/frontiernav#42]
react-redux@6.x uses React's new Context API for providing the store. This introduces a problematic side effect in that every `connect`ed component will now **always trigger an update**, even if nothing's changed. react-redux does not consider this a bug.

https://github.com/reduxjs/react-redux/issues/1136

This introduces issues with redux-little-router and a number of assumptions made with `componentDidUpdate` (in that, it's only called when props change).

react-redux recommends using React.memo, but that will be a lot of work.

In the meantime, frontiernav will have to stay on react-redux@5.x.

This issue is separate from #37.
The problem mentioned in #40 was caused by this.

**Comment by markerikson** [comment]
Hi.  If you have specific concerns over this behavior, please let us know what problems it's causing for you by filing an issue in the React-Redux repo.

**Comment by jahed** [comment]
No worries @markerikson. I regularly upgrade dependencies to catch issues like this and act on them later when I get the time. I'll submit an issue on your end once I understand it better.

**Comment by markerikson** [comment]
I'd hesitate to call it "plans to provide an API".

Some members of the community have put together some ideas, but we haven't actually evaluated those ideas, and there's no specific plans to actually incorporate those ideas atm.

**Comment by jahed** [comment]
Got ahead of myself :stuck_out_tongue: It's just an RFC.

Related issue, more to read:
https://github.com/reduxjs/react-redux/issues/1126

Might be easier at this point to just do the migration and list what breaks.

**Comment by jahed** [comment]
Over the last few months I've made enough changes to how components are written. Things that should've been in place anyway like using `reselect` to avoid doing the same calculations in `connect`. This seems to have fixed most of the unnecessary re-renders when using the latest `react-redux`.

The main thing is that `react-redux` now has a public export for the `ReactReduxContext` so `GameProvider` can access the `store` and call `replaceReducer` as normal.

I'll deploy an update and keep an eye on Rollbar for any rogue components causing issues.
